### ISSUE TITLE
Flag for debugging

### ISSUE THREAD

**Issue by dsw9742** [infinityworks/hpilo-exporter#3]
Hi there, nice exporter! 

I'm unable to scrape the /metrics endpoint with prometheus (or curl) but I'm able to get a successful result when I run the `get_embedded_health` command with `hpilo_cli`.

Is there a flag to turn on debugging for the hpilo-exporter server? I'm not super-familiar with Python so I'm hoping there's an easier way than instrumenting my own logging statements or figuring out how to set up a dev environment.

**Comment by BigValen** [comment]
That would be cool. I tried it, but I got 'empty reply from server' out of Curl. Some sort of debug output when credentials are wrong etc. would be good.

**Comment by Snegohod** [comment]
@dsw9742 upgrade iLO to last version and try my patch https://github.com/Snegohod/hpilo-exporter/commit/9c2ec482544fe28b648fc022273f67d03f09fec7
It`s works for me.

**Comment by Snegohod** [comment]
and this https://github.com/Snegohod/hpilo-exporter/commit/e8b647c8ba162aaad36dba3c079ca63b7fde6165

**Comment by Snegohod** [comment]
@dsw9742 replace line 115
`if ilo.get_fw_version()["management_processor"] == 'iLO3':`
to this string 
`if ilo.get_fw_version()["management_processor"] == 'iLO3' or ilo.get_fw_version()["management_processor"] == 'iLO2':`
should works, but very few metrics

**Comment by saied-nawaz** [comment]
Closing issue as it looks like the issue has been resolved
